# Generated by Django 4.2.2 on 2024-12-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "user"), ("admin", "administration")],
                default="пользователь",
                max_length=100,
            ),
        ),
    ]
